### ISSUE TITLE
bugs in review invites logic

### ISSUE THREAD

**Issue by alee** [comses/comses.net#471]
Looks like the template logic in 48cc37dd2557941d1539dbc816a15d151938859d introduced a bug when release.get_review() is None.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner                                                                                                                  response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 145, in _get_response                                                                                                              response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 143, in _get_response                                                                                                              response = response.render()
  File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 106, in render                                                                                                                      self.content = self.rendered_content
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/response.py", line 70, in rendered_content                                                                                                              ret = renderer.render(self.data, accepted_media_type, context)
  File "./core/renderers.py", line 26, in render
    return template.render(context, request=request)                                                                                                                                                                File "/usr/local/lib/python3.6/dist-packages/django_jinja/backend.py", line 106, in render
    return mark_safe(self.template.render(context))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/asyncsupport.py", line 76, in render                                                                                                                            return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1008, in render                                                                                                                           return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 780, in handle_exception                                                                                                                  reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 37, in reraise                                                                                                                                raise value.with_traceback(tb)
  File "library/templates/library/codebases/releases/retrieve.jinja", line 5, in top-level template code                                                                                                              {% set codebase = release.codebase %}
  File "core/templates/sidebar_layout.jinja", line 1, in top-level template code                                                                                                                                      {% extends 'base.jinja' %}
  File "core/templates/base.jinja", line 379, in top-level template code                                                                                                                                              {% block page %}
  File "core/templates/sidebar_layout.jinja", line 14, in block "page"
    {% block sidebar %}                                                                                                                                                                                             File "library/templates/library/codebases/releases/retrieve.jinja", line 339, in block "sidebar"
    {% set invite = review.get_invite(request.user.member_profile) if not request.user.is_anonymous else None %}                                                                                                  jinja2.exceptions.UndefinedError: 'None' has no attribute 'get_invite'
```

**Comment by alee** [comment]
fixed in 5302891af7f7ebd6a6b91434755dde56b80859b8
