### ISSUE TITLE
PIL error

### ISSUE THREAD

**Issue by alee** [comses/comses.net#554]
Possible image filesize issue with PIL: https://stackoverflow.com/questions/12984426/python-pil-ioerror-image-file-truncated-with-big-images

```
2020-12-28 03:22:13 ERROR   django.request:log_response:228 Internal Server Error: /users/3064/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wagtail/images/models.py", line 301, in get_rendition
    focal_point_key=cache_key,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
library.models.CodebaseRendition.DoesNotExist: CodebaseRendition matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "./core/renderers.py", line 26, in render
    return template.render(context, request=request)
  File "/usr/local/lib/python3.6/dist-packages/django_jinja/backend.py", line 59, in render
    return mark_safe(self._process_template(self.template.render, context, request))
  File "/usr/local/lib/python3.6/dist-packages/django_jinja/backend.py", line 105, in _process_template
    return handler(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "core/templates/core/member_profiles/retrieve.jinja", line 3, in top-level template code
    {% from "library/codebases/macros.jinja" import render_codebase_result, render_reviewer_feedback %}
  File "core/templates/sidebar_layout.jinja", line 1, in top-level template code
    {% extends 'base.jinja' %}
  File "core/templates/base.jinja", line 387, in top-level template code
    {% block page %}
  File "core/templates/sidebar_layout.jinja", line 10, in block "page"
    {% block content %}
  File "core/templates/core/member_profiles/retrieve.jinja", line 108, in block "content"
    {{ render_codebase_result(codebase) }}
  File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "library/templates/library/codebases/macros.jinja", line 56, in template
    {{ image(codebase.featured_images.first(), "fill-175x175", class="img-fluid img-thumbnail") }}
  File "/usr/local/lib/python3.6/dist-packages/wagtail/images/jinja2tags.py", line 23, in image
    rendition = get_rendition_or_not_found(image, filterspec)
  File "/usr/local/lib/python3.6/dist-packages/wagtail/images/shortcuts.py", line 13, in get_rendition_or_not_found
    return image.get_rendition(specs)
  File "/usr/local/lib/python3.6/dist-packages/wagtail/images/models.py", line 305, in get_rendition
    generated_image = filter.run(self, BytesIO())
  File "/usr/local/lib/python3.6/dist-packages/wagtail/images/models.py", line 415, in run
    willow = willow.auto_orient()
  File "/usr/local/lib/python3.6/dist-packages/willow/image.py", line 70, in wrapper
    image = converter(image)
  File "/usr/local/lib/python3.6/dist-packages/willow/plugins/pillow.py", line 231, in open
    image.load()
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFile.py", line 260, in load
    "image file is truncated "
OSError: image file is truncated (1 bytes not processed)
```

**Comment by alee** [comment]
resolved by removing offending Codebase with corrupted GIF
